### ISSUE TITLE
Regex issue

### ISSUE THREAD

**Issue by vijayhardaha** [75lb/renamer#53]
![image](https://user-images.githubusercontent.com/25227317/120890706-25c83e80-c622-11eb-8f7f-0320dc163454.png)

I am not sure if I am doing something wrong or regex is not working. I am trying to add prefixes to all the files in that folder. but this doesn't seem to work.

**Comment by vijayhardaha** [comment]
![image](https://user-images.githubusercontent.com/25227317/120890807-a4bd7700-c622-11eb-9f89-0eee4645c112.png)

I used the example in your doc. but this is also not working.

**Comment by 75lb** [comment]
Works for me (see below).. which OS are you on? Windows? Which shell are you using? 

```
$ renamer --find /0/ --replace="Hello - " --verbose --dry-run *

Dry run

✔︎ 01.jpg → Hello - 1.jpg
✔︎ 02.jpg → Hello - 2.jpg
✔︎ 03.jpg → Hello - 3.jpg

Rename complete: 3 of 3 files renamed.
```

**Comment by 75lb** [comment]
The same test as above also worked correctly in the Windows default shell (`cmd`).. However, it didn't work in Git Bash shell (cygwin), I will look into that.. which shell are you using?

**Comment by 75lb** [comment]
for some reason, on Git Bash, the shell inteprets `/1/` to mean the file `1` in the Git folder.. e.g. if you run this it will print the license from the `C:\Program Files\Git` folder 

```
cat '/LICENSE.txt'
```

That is not the expected behaviour.. oh well.. 

You can work around this issue by escaping the first backslash in the find expression (i.e. `--find "\/0/"`).. i'm not sure how to fix this long-term as I can't control what Git Bash passes into `renamer`..

**Comment by vijayhardaha** [comment]
Thanks for looking into this. I am using Git Bash on windows. escaping the first backslash solves the problem.
